srrescycgan:
  type: article
  title: "Deep Cyclic Generative Adversarial Residual Convolutional Networks for Real Image Super-Resolution"
  date: 2020-09-07
  author:
    - Muhhamad Umer, Rao
    - Micheloni, Christian
  serial:
    doi: "https://doi.org/10.48550/arXiv.2009.03693"

srrescgan:
  type: article
  title: "Deep Generative Adversarial Residual Convolutional Networks for Real-World Super-Resolution"
  date: 2020-05-03
  author:
    - Muhammad Umer, Rao
    - Micheloni, Christian
    - Luca Foresti, Gian
  serial:
    doi: "https://doi.org/10.48550/arXiv.2005.00953"

sr-with-mri:
  type: article
  title: "Super-resolution of magnetic resonance images using Generative Adversarial Networks"
  date: 2023-03-15
  author:
    - Guerreiro, João
    - Tomás, Pedro
    - Garcia, Nuno
    - Aidos, Helena
  serial:
    doi: "https://doi.org/10.1016/j.compmedimag.2023.102280"

cyclegan:
  type: article
  title: "Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks"
  date: 2020-08-24
  author:
    - Zhu, Jun-Yan
    - Park, Taesung
    - Isola, Phillip
    - Efros, Alexei A.
  serial:
    doi: "https://doi.org/10.48550/arXiv.1703.10593"

resnet:
  type: article
  title: "Deep Residual Learning for Image Recognition"
  date: 2015-12-10
  author:
    - He, Kaiming
    - Zhang, Xiangyu
    - Ren, Shaoqing
    - Sun, Jian
  serial:
    doi: "https://doi.org/10.48550/arXiv.1512.03385"

preactivation:
  type: web
  title: Pre-activation in Neural Networks
  author: Mortal, Meek
  date: 2017-01-04
  url: "https://learningstracker.wordpress.com/2017/01/04/pre-activation-in-neural-networks/"

instance-norm:
  type: article
  title: "Instance Normalization: The Missing Ingredient for Fast Stylization"
  date: 2017-11-06
  author:
    - Ulyanov, Dmitry
    - Vedaldi, Andrea
    - Lempitsky, Victor
  doi:
    serial: "https://doi.org/10.48550/arXiv.1607.08022"

logit:
  type: web
  title: Logit
  url: "https://en.wikipedia.org/wiki/Logit"

patch-gan:
  type: article
  title: "Patch-Based Image Inpainting with Generative Adversarial Networks"
  author:
    - Demir, Ugur
    - Unal, Gozde
  serial:
    doi: "https://doi.org/10.48550/arXiv.1803.07422"

kspace:
  type: web
  title: "What is k-space?"
  author: Elster, Allen D
  url: "https://mriquestions.com/what-is-k-space.html"
